version: "3"
services:
  gateway:
    build: ./gateway
    depends_on:
      - processing_requests
      - results_api
      - kafka
    ports:
      - "5003:5000"
  processing_requests:
    build: ./processing_requests
    depends_on:
      - processing_requests_db
      - kafka
    expose:
      - "5000"
    ports:
      - "5001:5000"
  processor:
    build: ./processor
    depends_on:
      - kafka
  results_listener:
    build: ./results_listener
    depends_on:
      - kafka
      - results_db
  results_api:
    build: ./results_api
    depends_on:
      - results_db
    expose:
      - "5000"
    ports:
      - "5002:5000"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "processing_requests_executions:1:1,successful_executions:1:1,failed_executions:1:1,dead_letter_queue:1:1"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    expose:
      - "2181"
    ports:
      - "2181:2181"
  processing_requests_db:
    image: mongo:latest
    container_name: processing_requests_db
    environment:
      MONGO_INITDB_DATABASE: processing_requests_db
      MONGO_INITDB_ROOT_USERNAME: processing_requests_user
      MONGO_INITDB_ROOT_PASSWORD: processing_requests_password
    expose:
      - "27017"
  results_db:
    image: mongo:latest
    container_name: results_db
    environment:
      MONGO_INITDB_DATABASE: results_db
      MONGO_INITDB_ROOT_USERNAME: results_user
      MONGO_INITDB_ROOT_PASSWORD: results_password
    expose:
      - "27017"
